### ISSUE TITLE
Meaning of Recall

### ISSUE THREAD

**Issue by jvamvas** [Helsinki-NLP/MuCoW#3]
Thank you for providing this great resource!
Could you help me understand the meaning of _recall_ in your evaluation protocol?

In your papers, you define precision and recall as follows:
![image](https://user-images.githubusercontent.com/5830820/103218673-fd724080-491b-11eb-8643-383d0b40f513.png)

Given those definitions, I would expect that recall is <= precision. However, in the results there are some rows where recall is actually greater than precision.

In the evaluation scripts, recall is computed as `pos / (pos+unk)`. This formula makes the results more plausible, but I have a hard time understanding it intuitively (whereas the definitions from the paper would make more sense to me, with the F1 as a middle stance between ignoring UNK, and treating all UNK as incorrect).

**Comment by yvesscherrer** [comment]
You're right, the evaluation scripts use a different definition from the one listed in the papers. The formula looks correct, and I cannot reconstruct anymore why the scripts use a different one. I've adapted the scripts to produce both variants: `RecallA = pos / (pos+unk)` and `RecallB = pos / (pos+unk+neg)`. I would recommend you to refer to `RecallB` if you plan to use MuCoW.

**Comment by jvamvas** [comment]
@yvesscherrer Thank you for the reply!
